config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :country, :cost, :presence => true

  scope :five_most_recent, -> { order(created_at: :desc).limit(5) }
  scope :made_in_usa, -> { where("country like ?", "United States") }
  scope :five_most_reviewed, -> {(
    select("products.id, products.name, products.country, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(5)
  )}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  validates :author, :presence => true
  validates :rating, :presence => true
  validates :content_body, :presence => true

  validates :content_body, length: { in: 50..250 }
  validates_inclusion_of :rating, :in => 1..5

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "Product has been deleted"
    redirect_to products_path
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def update
    binding.pry
    @product= Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product has been updated"
      redirect_to products_path
    else
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:country, :cost, :name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    @review.product_id = @product.id
    if @review.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  # def update
  #   @review= Review.find(params[:id])
  #   if @review.update(review_params)
  #     flash[:notice] = "Product has been updated"
  #     redirect_to reviews_path
  #   else
  #     render :edit
  #   end
  # end

  def destroy
    Review.find(params[:id]).destroy
  end

  private

  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marios</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= bootstrap_form_for @product do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :country %>
  <%= f.number_field :cost %>
  <%= f.submit %>
<% end %>

app/views/products/index.html.erb
<h2>Welcome to Mario's global foods! We gather foods from all of the world for your enjoyment!</h2><br>

<hr>
<h2><%= link_to("Make new product", new_product_path) %></h2>

<hr>
<h4>Recently Added:</h4>
<% @products.five_most_recent.each do |product| %>
  <br>
  <li>
    <%= link_to(product.name, product_path(product)) %><%= " from #{product.country}, for $#{product.cost}" %> &ensp;&ensp;|&ensp;&ensp;
    <%= link_to "Remove", product_path(product), data: { confirm: 'Are you certain you want to delete this?', method: :delete }%> | <%= link_to "Update", product_path(product), method: :patch %>
  </li>
<% end %>
<br><hr>

<h4>Most Reviewed:</h4>
<% @products.five_most_reviewed.each do |product| %>
  <br>
  <li>
    <%= link_to(product.name, product_path(product)) %><%#= " from #{product.country}, for $#{product.cost}" %> &ensp;&ensp;|&ensp;&ensp;
    <%= link_to "Remove", product_path(product), data: { confirm: 'Are you certain you want to delete this?', method: :delete }%> | <%= link_to "Update", product_path(product), method: :patch %>
  </li>
<% end %>
<br><hr>

<h4>Made in the US of A:</h4>
<% @products.made_in_usa.each do |product| %>
  <br>
  <li>
    <%= link_to(product.name, product_path(product)) %><%= " from #{product.country}, for $#{product.cost}" %> &ensp;&ensp;|&ensp;&ensp;
    <%= link_to "Remove", product_path(product), data: { confirm: 'Are you certain you want to delete this?', method: :delete }%> | <%= link_to "Update", product_path(product), method: :patch %>
</li>
<% end %>

<p>
  What, you didn't see that this is Mario's <i><b>global</b></i> foods?
</p>
<br><hr>

<h4>The Whole Shebang:</h4>
<% @products.each do |product| %>
  <br>
  <li>
    <%= link_to(product.name, product_path(product)) %><%= " from #{product.country}, for $#{product.cost}" %> &ensp;&ensp;|&ensp;&ensp;
    <%= link_to "Remove", product_path(product), data: { confirm: 'Are you certain you want to delete this?', method: :delete }%> | <%= link_to "Update", product_path(product), method: :patch %>
</li>
<% end %>

app/views/products/new.html.erb
<h3>Add a product:</h3>
<br>

<%= render partial: 'form' %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h3><i><%= @product.country %></i>, $<%= @product.cost %></h3>

<hr>

<% if @product.reviews.any? %>
  <h1>Reviews of <%= @product.name %>: </h1><br>
  <% @product.reviews.each do |review| %>
    <h2><%= review.author %></h2>
    <% review.rating.times do |star| %>
      &#9733;
    <% end %>
    <% (5 - review.rating).times do |star| %>
      &#9734;
    <% end %>
    <p>
      <%= review.content_body %>
    </p>
    <%= link_to("Delete", product_review_path(@product, review), :data => {:confirm => "Are you sure?", :method => "delete"}) %><br>
  <% end %>
<% end %>
<hr>
<%= link_to("Add a review", new_product_review_path(@product)) %>
<br>
<%= link_to("Home", products_path) %>

app/views/reviews/_form.erb
<%= render "layouts/errors", :object => @review %>

<%= bootstrap_form_for [@product, @review] do |f| %>
  <%= f.text_field :author %>
  <%= f.text_field :content_body%>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<h3>Add a review:</h3>
<br>

<%= render partial: 'form' %>